CI: try revoking oauth client

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -201,7 +201,7 @@ jobs:
           ts-audience: ${{ secrets.TS_AUDIENCE }}
           ts-tags: ${{ secrets.TS_TAGS }}
 
-      - name: Request Tailscale API token using WIF credentials
+      - name: First request Tailscale API token using WIF credentials
         id: ts-token-exchange
         if: steps.check-label-skip.outputs.label_present == 'false'
         run: |
@@ -254,6 +254,7 @@ jobs:
           echo "client_id=$client_id" >> $GITHUB_OUTPUT
           echo "client_secret=$client_secret" >> $GITHUB_OUTPUT
 
+
       # TODO: uncomment
       #- name: Run Terratest
       #  if: steps.check-label-skip.outputs.label_present == 'false'
@@ -263,23 +264,33 @@ jobs:
       #    TAILSCALE_OAUTH_CLIENT_SECRET: ${{ steps.ts-oauth-create.outputs.client_secret }}
       #  run: go test -v ./tests/... -timeout ${{ env.TERRATEST_TIMEOUT }}
 
-      #- name: Revoke temporary Tailscale OAuth client
-      #  if: always() && steps.ts-oauth-create.outputs.client_id != ''
-      #  env:
-      #    CLIENT_ID: ${{ steps.ts-oauth-create.outputs.client_id }}
-      #    CLIENT_SECRET: ${{ steps.ts-oauth-create.outputs.client_secret }}
-      #  run: |
-      #    token_response=$(curl -sS 'https://api.tailscale.com/api/v2/oauth/token' \
-      #      --request POST \
-      #      --header 'Content-Type: application/x-www-form-urlencoded' \
-      #      --data-urlencode "grant_type=client_credentials" \
-      #      --data-urlencode "client_id=$CLIENT_ID" \
-      #      --data-urlencode "client_secret=$CLIENT_SECRET")
-      #    echo "token response: $token_response"
-      #    ts_token=$(echo "$token_response" | jq -r '.access_token')
+      - name: Second request Tailscale API token using WIF credentials
+        id: ts-token-exchange-2
+        if: steps.check-label-skip.outputs.label_present == 'false'
+        run: |
+          response=$(curl -X POST https://api.tailscale.com/api/v2/oauth/token-exchange \
+            -H "Content-Type: application/x-www-form-urlencoded" \
+            -d "client_id=$TAILSCALE_OAUTH_CLIENT_ID" \
+            -d "jwt=$TAILSCALE_IDENTITY_TOKEN")
 
-      #    delete_response=$(curl -sS "https://api.tailscale.com/api/v2/tailnet/-/keys/$CLIENT_ID" \
-      #      --request DELETE \
-      #      --header "Authorization: Bearer $ts_token")
-      #    echo "delete response: $delete_response"
+          ts_token=$(echo "$response" | jq -r '.access_token')
+
+          if [ -z "$ts_token" ] || [ "$ts_token" = "null" ]; then
+            echo "ERROR: token exchange failed"
+            exit 1
+          fi
+
+          echo "::add-mask::$ts_token"
+          echo "ts_token=$ts_token" >> $GITHUB_OUTPUT
+
+      - name: Revoke temporary Tailscale OAuth client
+        if: always() && steps.ts-oauth-create.outputs.client_id != ''
+        env:
+          TS_TOKEN: ${{ steps.ts-token-exchange-2.outputs.ts_token }}
+          CLIENT_ID: ${{ steps.ts-oauth-create.outputs.client_id }}
+        run: |
+          delete_response=$(curl -sS "https://api.tailscale.com/api/v2/tailnet/-/keys/$CLIENT_ID" \
+            --request DELETE \
+            --header "Authorization: Bearer $TS_TOKEN")
+          echo "delete response: $delete_response"
 
